# Generated by Django 5.0.6 on 2024-06-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_description_en_task_description_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description_ky',
            new_name='description_kr',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title_ky',
            new_name='title_kr',
        ),
    ]
